// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvTJR8pE3aPRD6Z3ibFCvbTpnXihs08MM',
    appId: '1:279791437227:web:42f3dae019a993e741feee',
    messagingSenderId: '279791437227',
    projectId: 'massage-pos-4fb5b',
    authDomain: 'massage-pos-4fb5b.firebaseapp.com',
    storageBucket: 'massage-pos-4fb5b.firebasestorage.app',
    measurementId: 'G-2H37Q13B7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_4fljHHugnSZvutfTGYZTtvH90NVaLUw',
    appId: '1:279791437227:android:80374be3d1dff51441feee',
    messagingSenderId: '279791437227',
    projectId: 'massage-pos-4fb5b',
    storageBucket: 'massage-pos-4fb5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeeIvjjlESPwoL69_J-pcaScDPRCaYCSo',
    appId: '1:279791437227:ios:dd108b546d7c57de41feee',
    messagingSenderId: '279791437227',
    projectId: 'massage-pos-4fb5b',
    storageBucket: 'massage-pos-4fb5b.firebasestorage.app',
    iosBundleId: 'com.example.employeeAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeeIvjjlESPwoL69_J-pcaScDPRCaYCSo',
    appId: '1:279791437227:ios:dd108b546d7c57de41feee',
    messagingSenderId: '279791437227',
    projectId: 'massage-pos-4fb5b',
    storageBucket: 'massage-pos-4fb5b.firebasestorage.app',
    iosBundleId: 'com.example.employeeAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvTJR8pE3aPRD6Z3ibFCvbTpnXihs08MM',
    appId: '1:279791437227:web:f0e066698cb1104a41feee',
    messagingSenderId: '279791437227',
    projectId: 'massage-pos-4fb5b',
    authDomain: 'massage-pos-4fb5b.firebaseapp.com',
    storageBucket: 'massage-pos-4fb5b.firebasestorage.app',
    measurementId: 'G-HXMDFM42KE',
  );
}
